spec:
  template:
    spec:
      containers:
      - name: analysis-service
        readinessProbe:
          httpGet:
            path: /check-ip?ip=1.1.1.1
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
