apiVersion: v1
kind: Namespace
metadata:
  name: ip-checker
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: ip-checker
spec:
  selector:
    app: mongodb
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: ip-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  namespace: ip-checker
spec:
  selector:
    app: auth-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: ip-checker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ntvs28/auth-service:v1
        ports:
        - containerPort: 8001
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/authdb
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-service
  namespace: ip-checker
spec:
  selector:
    app: api-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
  namespace: ip-checker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: ntvs28/api-service:v1
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/apidb
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web-service
  namespace: ip-checker
spec:
  selector:
    app: frontend-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-deployment
  namespace: ip-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
      - name: frontend-web
        image: ntvs28/frontend-web:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service-service
  namespace: ip-checker
spec:
  selector:
    app: analysis-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service-deployment
  namespace: ip-checker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
    spec:
      containers:
      - name: analysis-service
        image: ntvs28/analysis-service:v1
        ports:
        - containerPort: 8002
